[context.develop.environment]
  REACT_APP_ENABLED_SECTIONS = "*"

[context.production.environment]
  REACT_APP_ENABLED_SECTIONS = "Stories,Event,Gifts"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
