[context.develop.environment]
  REACT_APP_ENABLED_SECTIONS = "Stories,Giving,Recipes"
  REACT_APP_ROBOTS_SETTING = "noindex,nofollow"

[context.production.environment]
  REACT_APP_ENABLED_SECTIONS = "Stories,Event,Gifts"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
