[context.develop.environment]
  REACT_APP_ENABLED_SECTIONS = "Photos,Stories,Giving,Recipes"
  REACT_APP_ROBOTS_SETTING = "noindex,nofollow"

[context.production.environment]
  REACT_APP_ENABLED_SECTIONS = "Photos,Stories,Giving,Recipes"
  REACT_APP_CROWDRISE_REFRESH_INTERVAL = "60000"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
